#
# True metrics used for accuracy calculation by metric_extractor.py
#

TRUE_METRICS = {
    "NextEra Energy Inc 2024 Sustainability Report (SustainabilityReports.com).pdf": [
  {"metric_id": 1,  "metric_name": "Waste generated - Hazardous [metric ton]", "value": 11.6, "unit": "metric ton", "reported_year": 2023, "status": "ok"},
  {"metric_id": 2,  "metric_name": "Waste generated - Non Hazardous [metric ton]", "value": None, "unit": "metric ton", "reported_year": None, "status": "not_found_in_report_snippets"},
  {"metric_id": 3,  "metric_name": "Diverted Waste from Disposal (reused, recycled, recovered) [metric ton]", "value": None, "unit": "metric ton", "reported_year": None, "status": "not_found_in_report_snippets"},

  {"metric_id": 4,  "metric_name": "Water withdrawal [m3]", "value": 7900212000, "unit": "m3", "reported_year": 2023, "status": "ok"},

  {"metric_id": 5,  "metric_name": "Total FRESH water discharge (<= 1,000mg/L TDS) [m3]", "value": None, "unit": "m3", "reported_year": None, "status": "not_found_in_report_snippets"},
  {"metric_id": 6,  "metric_name": "Total OTHER water discharge (>= 1,000mg/L TDS) [m3]", "value": None, "unit": "m3", "reported_year": None, "status": "not_found_in_report_snippets"},
  {"metric_id": 7,  "metric_name": "Water Recycled or Reused [m3]", "value": None, "unit": "m3", "reported_year": None, "status": "not_found_in_report_snippets"},

  {"metric_id": 18, "metric_name": "Total energy generated by the company [MWh]", "value": 238758624, "unit": "MWh", "reported_year": 2023, "status": "ok"},
  {"metric_id": 19, "metric_name": "Total non fossil fuel energy generated by the company [MWh]", "value": 129461864, "unit": "MWh", "reported_year": 2023, "status": "ok"},

  {"metric_id": 23, "metric_name": "Total direct GHG emissions [tCO2e]", "value": 42278597, "unit": "tCO2e", "reported_year": 2023, "status": "ok"},

  {"metric_id": 24, "metric_name": "Total energy indirect GHG emissions [tCO2e]", "value": 16300, "unit": "tCO2e", "reported_year": 2023, "basis": "market-based", "status": "ok"},

  {"metric_id": 25, "metric_name": "Total use of products [metric tons CO2 equilvalent tCO2e]", "value": None, "unit": "tCO2e", "reported_year": None, "status": "not_isolated_in_context"},
  {"metric_id": 27, "metric_name": "Emissions neutralized by Carbon Offset Projects [tCO2e]", "value": None, "unit": "tCO2e", "reported_year": None, "status": "not_found_in_report_snippets"},
  {"metric_id": 28, "metric_name": "Emissions of ozone-depleting substances (ODS) [metric tons of CFC-11]", "value": None, "unit": "metric tons of CFC-11", "reported_year": None, "status": "not_found_in_report_snippets"},
  {"metric_id": 29, "metric_name": "Nitrogen oxides [NOX], sulfur oxides [SOX] and other significant air emissions [tons NOx + Sox]", "value": 8683, "unit": "tons NOx + Sox", "reported_year": 2023, "status": "ok"},
  {"metric_id": 30, "metric_name": "Spillage and fines [$]", "value": None, "unit": "$", "reported_year": None, "status": "not_found_in_report_snippets"},
  {"metric_id": 31, "metric_name": "Volume of flared hydrocarbon [tCO2e]", "value": None, "unit": "tCO2e", "reported_year": None, "status": "not_found_in_report_snippets"},
  {"metric_id": 32, "metric_name": "Volume of vented hydrocarbon [tCO2e]", "value": None, "unit": "tCO2e", "reported_year": None, "status": "not_found_in_report_snippets"}
  ]

    
}