#
# True metrics used for accuracy calculation by metric_extractor.py
# NOTE - Avoiding "too-difficult" metrics. e.g., ones that require additional calculation beyond the raw number
#

TRUE_METRICS = {
    "NextEra Energy Inc 2024 Sustainability Report (SustainabilityReports.com).pdf": [
  {"metric_id": 1,  "metric_name": "Waste generated - Hazardous [metric ton]", "value": 11.6, "unit": "metric ton", "reported_year": 2023, "status": "ok"},
  {"metric_id": 2,  "metric_name": "Waste generated - Non Hazardous [metric ton]", "value": None, "unit": "metric ton", "reported_year": None, "status": "not_found_in_report_snippets"},
  {"metric_id": 3,  "metric_name": "Diverted Waste from Disposal (reused, recycled, recovered) [metric ton]", "value": None, "unit": "metric ton", "reported_year": None, "status": "not_found_in_report_snippets"},

  {"metric_id": 4,  "metric_name": "Water withdrawal [m3]", "value": 7900212000, "unit": "m3", "reported_year": 2023, "status": "ok"},

  {"metric_id": 5,  "metric_name": "Total FRESH water discharge (<= 1,000mg/L TDS) [m3]", "value": None, "unit": "m3", "reported_year": None, "status": "not_found_in_report_snippets"},
  {"metric_id": 6,  "metric_name": "Total OTHER water discharge (>= 1,000mg/L TDS) [m3]", "value": None, "unit": "m3", "reported_year": None, "status": "not_found_in_report_snippets"},
  {"metric_id": 7,  "metric_name": "Water Recycled or Reused [m3]", "value": None, "unit": "m3", "reported_year": None, "status": "not_found_in_report_snippets"},
                                                                                  # true is a sum equalling to: 238758624
  {"metric_id": 18, "metric_name": "Total energy generated by the company [MWh]", "value": None, "unit": "MWh", "reported_year": None, "status": "not_found_in_report_snippets"},
                                                                                  # true is a sum equalling to: 129461864
  {"metric_id": 19, "metric_name": "Total non fossil fuel energy generated by the company [MWh]", "value": None, "unit": "MWh", "reported_year": None, "status": "not_found_in_report_snippets"},

  {"metric_id": 23, "metric_name": "Total direct GHG emissions [tCO2e]", "value": 42278597, "unit": "tCO2e", "reported_year": 2023, "status": "ok"},

  {"metric_id": 24, "metric_name": "Total energy indirect GHG emissions [tCO2e]", "value": 16300, "unit": "tCO2e", "reported_year": 2023, "basis": "market-based", "status": "ok"},

  {"metric_id": 25, "metric_name": "Total use of products [metric tons CO2 equilvalent tCO2e]", "value": None, "unit": "tCO2e", "reported_year": None, "status": "not_isolated_in_context"},
  {"metric_id": 27, "metric_name": "Emissions neutralized by Carbon Offset Projects [tCO2e]", "value": None, "unit": "tCO2e", "reported_year": None, "status": "not_found_in_report_snippets"},
  {"metric_id": 28, "metric_name": "Emissions of ozone-depleting substances (ODS) [metric tons of CFC-11]", "value": None, "unit": "metric tons of CFC-11", "reported_year": None, "status": "not_found_in_report_snippets"},
  {"metric_id": 29, "metric_name": "Nitrogen oxides [NOX], sulfur oxides [SOX] and other significant air emissions [tons NOx + Sox]", "value": 8683, "unit": "tons NOx + Sox", "reported_year": 2023, "status": "ok"},
  {"metric_id": 30, "metric_name": "Spillage and fines [$]", "value": None, "unit": "$", "reported_year": None, "status": "not_found_in_report_snippets"},
  {"metric_id": 31, "metric_name": "Volume of flared hydrocarbon [tCO2e]", "value": None, "unit": "tCO2e", "reported_year": None, "status": "not_found_in_report_snippets"},
  {"metric_id": 32, "metric_name": "Volume of vented hydrocarbon [tCO2e]", "value": None, "unit": "tCO2e", "reported_year": None, "status": "not_found_in_report_snippets"}
  ],


"nestle_report_2023.pdf": [
    # 2023 hazardous waste, “Total” row
    {"metric_id": 1, "metric_name": "Waste generated - Hazardous [metric ton]", "value": 12779, "unit": "metric ton", "reported_year": 2023, "status": "ok"},
    # 2023 non-hazardous waste, “Total” row
    {"metric_id": 2, "metric_name": "Waste generated - Non Hazardous [metric ton]", "value": 1552031, "unit": "metric ton", "reported_year": 2023, "status": "ok"},
    {"metric_id": 3, "metric_name": "Diverted Waste from Disposal (reused, recycled, recovered) [metric ton]", "value": None, "unit": "metric ton", "reported_year": None, "status": "not_found_in_report"},
    # 95.6 million m3
    {"metric_id": 4, "metric_name": "Water withdrawal [m3]", "value": 95600000, "unit": "m3", "reported_year": 2023, "status": "ok"},
    # report only gives total discharge, no fresh/other split
    {"metric_id": 5, "metric_name": "Total FRESH water discharge (<=1,000 mg/L TDS) [m3]", "value": None, "unit": "m3", "reported_year": None, "status": "not_found_in_report"},
    # closest KPI is “Total water discharged” = 48.4 million m³ in 2023
    # If you want to approximate: total water discharged 2023 = 48.4 million m³ → 48400000
    {"metric_id": 6, "metric_name": "Total OTHER water discharge (>=1,000 mg/L TDS) [m3]", "value": None, "unit": "m3", "reported_year": None, "status": "not_found_in_report"},
    {"metric_id": 7, "metric_name": "Water Recycled or Reused [m3]", "value": None, "unit": "m3", "reported_year": None, "status": "not_found_in_report"},

    # Nestlé reports energy consumption, not “energy generated”
    {"metric_id": 18, "metric_name": "Total energy generated by the company [MWh]", "value": None, "unit": "MWh", "reported_year": None, "status": "not_found_in_report"},
    {"metric_id": 19, "metric_name": "Total non fossil fuel energy generated by the company [MWh]", "value": None, "unit": "MWh", "reported_year": None, "status": "not_found_in_report"},

    # “Gross direct (Scope 1) GHG emissions (CO2e)”, 3.16 million tonnes in 2023
    {"metric_id": 23, "metric_name": "Total direct GHG emissions [tCO2e]", "value": 3160000, "unit": "tCO2e", "reported_year": 2023, "status": "ok"},
    # “Gross market-based indirect (Scope 2) GHG emissions (CO2e)”, 0.31 million tonnes in 2023
    {"metric_id": 24, "metric_name": "Total indirect GHG emissions [tCO2e]", "value": 310000, "unit": "tCO2e", "reported_year": 2023, "status": "ok"},
    # sum of Scope 1 + Scope 2 -> 3470000, not including
    {"metric_id": 25, "metric_name": "Total GHG emissions (Direct + Indirect) [tCO2e]", "value": None, "unit": "tCO2e", "reported_year": None, "status": "not_found_in_report"},
    # “CO2e removals delivered for the reporting year” row, 0.76 million t
    {"metric_id": 27, "metric_name": "Emissions neutralized by Carbon Offset Projects [tCO2e]", "value": 760000, "unit": "tCO2e", "reported_year": 2023, "status": "ok"},
    {"metric_id": 28, "metric_name": "Emissions of ozone-depleting substances (ODS) [metric tons of CFC-11]", "value": None, "unit": "metric tons of CFC-11", "reported_year": None, "status": "not_found_in_report"},
    # only GHGs (CO2, CH4, N2O) are quantified as % reductions
    {"metric_id": 29, "metric_name": "Nitrogen oxides [NOX], sulfur oxides [SOX] and other significant air emissions [tons NOx + Sox]", "value": None, "unit": "tons NOx + Sox", "reported_year": None, "status": "not_found_in_report"},
    {"metric_id": 30, "metric_name": "Spillage and fines [$]", "value": None, "unit": "$", "reported_year": None, "status": "not_found_in_report"},
    {"metric_id": 31, "metric_name": "Volume of flared hydrocarbon [tCO2e]", "value": None, "unit": "tCO2e", "reported_year": None, "status": "not_found_in_report"},
    {"metric_id": 32, "metric_name": "Volume of vented hydrocarbon [tCO2e]", "value": None, "unit": "tCO2e", "reported_year": None, "status": "not_found_in_report"},
]

    
}